---
title: "Limited information Goodness-of-Fit tests"
author: Haziq Jamil
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Limited information Goodness-of-Fit tests}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(plFA)
library(lavaan.bingof)
```

```{r}
(dat <- gen_data_bin(n = 1000, seed = 123))
mod <- "eta =~ y1 + y2 + y3 + y4 + y5"
fit <- cfa(mod, dat, std.lv = TRUE)
tinytest::expect_true(inherits(fit, "plFAlavaan"))

# Test statistics
all_tests(fit)
```

Most tests look fine, except the Wald and WaldDiag -- both of which rely on the $\Omega_2$ matrix.
<!-- This means either the $\Omega_2$ matrix or the fitted probabilities (or both!) are off.  -->
Let's do some checking.

Check first the probabilities and proportions.

```{r}
x <- lavaan.bingof::get_uni_bi_moments(fit)  # plFA
y <- lavaan.bingof::get_uni_bi_moments(  # lavaan
  lavaan::cfa(mod, dat, std.lv = TRUE)
)  
tinytest::expect_equal(x, y, tolerance = 1e-4)
```

Check the $H^{-1}$ matrix.

```{r}
Hinv1 <- computeVar(fit@external$plFA, fit@external$D)$invH
Hinv2 <- lavaan.bingof:::get_sensitivity_inv_mat(fit)
tinytest::expect_equal(Hinv1, Hinv2)

# lavaan:::lav_model_hessian(
#     lavmodel = fit@Model,
#     lavsamplestats = fit@SampleStats,
#     lavdata = fit@Data,
#     lavoptions = fit@Options
# )
```

So both are off.
I think we should check the PML fit using lavaan package first.

```{r}
fit1 <- plFA::cfa(mod, dat, std.lv = TRUE)
fit2 <- lavaan::cfa(mod, dat, std.lv = TRUE, estimator = "PML")
tinytest::expect_equal(coef(fit1), coef(fit2), tolerance = 1e-5)
tinytest::expect_equal(fit1@Fit@Sigma.hat, fit2@Fit@Sigma.hat, tolerance = 1e-5)
```

Test extracted lavaan stuff:

```{r}
x <- lavaan.bingof:::extract_lavaan_info(fit1)
y <- lavaan.bingof:::extract_lavaan_info(fit2)
tinytest::expect_equal(x, y, tolerance = 1e-4)
```

Differences in test statistic values.

```{r}
c("Wald_test", "Wald_vcovf_test", "Wald_diag_test", "Pearson_test", "RSS_test", "Multn_test") |>
  purrr::set_names() |>
  purrr::map(.f = function(x) {
    out1 <- do.call(x, list(fit1))
    out2 <- do.call(x, list(fit2))
    tinytest::expect_equal(out1, out2, tolerance = 1e-2)
  })
```

