# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Single pair contribution
#'
#' @description
#' Wrapper of pair_contribution() used for unit tests
#'
#' @param A Constraint matrix. Loadings free to be estimated are identified by a 1.
#' @param C_VEC Vector containing the number of categories for each item
#' @param THETA Parameter vector
#' @param CORRFLAG 1 to estimate latent correlations. 0 for orthogonal latent factors.
#' @param k first index identifying the pair
#' @param l second index identifying the pair
#' @param PAIRS_TABLE output from [pairs_freq()]
#' @param SILENTFLAG optional for verbose output
#' @param GRADFLAG 1 to compute gradient
cpp_compute_pair_ext <- function(CONSTRMAT, CONSTRLOGSD, C_VEC, THETA, CORRFLAG, NTHR, NLOAD, NCORR, NVAR, K, L, PAIRS_TABLE, SILENTFLAG, GRADFLAG, OPTION = 0L) {
    .Call(`_plFA_cpp_compute_pair_ext`, CONSTRMAT, CONSTRLOGSD, C_VEC, THETA, CORRFLAG, NTHR, NLOAD, NCORR, NVAR, K, L, PAIRS_TABLE, SILENTFLAG, GRADFLAG, OPTION)
}

#' @export
cpp_loadings_theta2vec <- function(THETA, NTHR, NLOAD) {
    .Call(`_plFA_cpp_loadings_theta2vec`, THETA, NTHR, NLOAD)
}

#' @export
cpp_loadings_theta2mat <- function(THETA, CONSTRMAT, NTHR, NLOAD) {
    .Call(`_plFA_cpp_loadings_theta2mat`, THETA, CONSTRMAT, NTHR, NLOAD)
}

#' @export
cpp_loadings_mat2vec <- function(LOADINGS, CONSTRMAT, NLOAD) {
    .Call(`_plFA_cpp_loadings_mat2vec`, LOADINGS, CONSTRMAT, NLOAD)
}

#' @export
cpp_latvar_vec2cmat <- function(VEC, NCORR, Q) {
    .Call(`_plFA_cpp_latvar_vec2cmat`, VEC, NCORR, Q)
}

#' @export
cpp_latvar_vec2dmat <- function(VEC, CONSTRLOGSD, NCORR, NVAR, Q) {
    .Call(`_plFA_cpp_latvar_vec2dmat`, VEC, CONSTRLOGSD, NCORR, NVAR, Q)
}

#' @export
cpp_latvar_theta2cmat <- function(THETA, NTHR, NLOAD, NCORR, NVAR, Q) {
    .Call(`_plFA_cpp_latvar_theta2cmat`, THETA, NTHR, NLOAD, NCORR, NVAR, Q)
}

#' @export
cpp_latvar_theta2dmat <- function(THETA, CONSTRLOGSD, NTHR, NLOAD, NCORR, NVAR, Q) {
    .Call(`_plFA_cpp_latvar_theta2dmat`, THETA, CONSTRLOGSD, NTHR, NLOAD, NCORR, NVAR, Q)
}

#' @export
cpp_latvar_theta2mat <- function(THETA, CONSTRLOGSD, NTHR, NLOAD, NCORR, NVAR, Q) {
    .Call(`_plFA_cpp_latvar_theta2mat`, THETA, CONSTRLOGSD, NTHR, NLOAD, NCORR, NVAR, Q)
}

#' @export
cpp_latvar_mat2vec <- function(S, CONSTRLOGSD, NCORR, NVAR) {
    .Call(`_plFA_cpp_latvar_mat2vec`, S, CONSTRLOGSD, NCORR, NVAR)
}

#' @export
cpp_latvar_mat2cmat <- function(S) {
    .Call(`_plFA_cpp_latvar_mat2cmat`, S)
}

#' Compute pairwise frequencies
#'
#' It returns a 5-rows matrix with each combination of items and categories as columns.
#' Row0: item k, Row1: item l, Row2; category item k, Row3: category item l, Row4: freq
#' It is computed just once, before the optimization of the complete pairwise
#'
#' @param Y Integer matrix of dimension \eqn{n*p}, where \eqn{n} is the sample size
#' and \eqn{p} is the number of items considered. Categories must be coded starting from zero.
#' For example, an item with three categories can only accept values contained in
#' \eqn{\{0, 1, 2\}}.
#' @param C_VEC Integer vector indicating how many possible categories are associated to
#' each item in 'Y'.
#' @export
pairs_freq <- function(Y, C_VEC) {
    .Call(`_plFA_pairs_freq`, Y, C_VEC)
}

#' Full pairwise iteration
#'
#' @description
#' Evaluate negative loglikelihood or gradient of the complete pool of pairs.
#' Used by external optimisers. Multithreading options via `RcppParallel`.
#'
#' @param N Number of observations
#' @param C_VEC Vector containing the number of categories for each item
#' @param CONSTRMAT Constraint matrix. Loadings free to be estimated are identified by a NA.
#' @param THETA Parameter vector
#' @param FREQ Frequency table
#' @param CORRFLAG 1 to estimate latent correlations. 0 for orthogonal latent factors.
#' @param GRFLAG 0 to only compute the likelihood. 1 to also compute the gradient.
#' @param SILENTFLAG optional for verbose output
#'
cpp_multiThread_completePairwise <- function(N, C_VEC, CONSTRMAT, CONSTRLOGSD, THETA, FREQ, CORRFLAG, NTHR, NLOAD, NCORR, NVAR, GRFLAG = 0L, SILENTFLAG = 1L) {
    .Call(`_plFA_cpp_multiThread_completePairwise`, N, C_VEC, CONSTRMAT, CONSTRLOGSD, THETA, FREQ, CORRFLAG, NTHR, NLOAD, NCORR, NVAR, GRFLAG, SILENTFLAG)
}

sampling_step <- function(FULL_POOL, METHODFLAG, PROB, PAIRS_PER_ITERATION, N_ITEMS, SEED, SILENTFLAG, ITER) {
    .Call(`_plFA_sampling_step`, FULL_POOL, METHODFLAG, PROB, PAIRS_PER_ITERATION, N_ITEMS, SEED, SILENTFLAG, ITER)
}

#' Estimate of H
#'
#' @description
#' Compute a sample estimate of the expected negative Hessian by taking
#' advantage of the second Bartlett's identity at the single pair level
#'
#' @param A Constraint matrix. Loadings free to be estimated are identified by a 1.
#' @param C_VEC Vector containing the number of categories for each item
#' @param THETA Parameter vector
#' @param CORRFLAG 1 to estimate latent correlations. 0 for orthogonal latent factors.
#' @param FREQ output from [pairs_freq()]
#' @param N sample size
estimate_H <- function(C_VEC, A, THETA, FREQ, N, CORRFLAG) {
    .Call(`_plFA_estimate_H`, C_VEC, A, THETA, FREQ, N, CORRFLAG)
}

#' Estimate of J
#'
#' @description
#' Compute a sample estimate of the variability matrix via the sample average outer product
#' of the composite score
#'
#' @param A Constraint matrix. Loadings free to be estimated are identified by a 1.
#' @param C_VEC Vector containing the number of categories for each item
#' @param THETA Parameter vector
#' @param CORRFLAG 1 to estimate latent correlations. 0 for orthogonal latent factors.
#' @param Y data matrix
estimate_J <- function(Y, C_VEC, A, CONSTRLOGSD, THETA, CORRFLAG, NTHR, NLOAD, NCORR, NVAR) {
    .Call(`_plFA_estimate_J`, Y, C_VEC, A, CONSTRLOGSD, THETA, CORRFLAG, NTHR, NLOAD, NCORR, NVAR)
}

