# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute pairwise frequencies
#'
#' It returns a 5-rows matrix with each combination of items and categories as columns.
#' Row0: item k, Row1: item l, Row2; category item k, Row3: category item l, Row4: freq
#' It is computed just once, before the optimization of the complete pairwise
#'
#' @param Y Integer matrix of dimension \eqn{n*p}, where \eqn{n} is the sample size
#' and \eqn{p} is the number of items considered. Categories must be coded starting from zero.
#' For example, an item with three categories can only accept values contained in
#' \eqn{\{0, 1, 2\}}.
#' @param C_VEC Integer vector indicating how many possible categories are associated to
#' each item in 'Y'.
pairs_freq <- function(Y, C_VEC) {
    .Call(`_plFA_pairs_freq`, Y, C_VEC)
}

#' Get loading matrix from theta
#'
#' get_Lam() constructs the loading matrix from the parameter vector
#'
#' @param THETA Numerical vector of parameters.
#' @param A Binary matrix of dimension \eqn{p*q} where \eqn{p} is the number
#' of items and \eqn{q} the number of latent variables. Entries equal to
#' \eqn{1} refer to free loadings, while entries equal to \eqn{0} indicate
#' loadings constrained to be null.
#' @param C Sum of the number of categories for each item.
NULL

#' Get latent correlation matrix from theta
#'
#' get_Sigma_u() extracts the latent correlation matrix from theta assuming
#' theta elements to be reparametrised following the
#' Lewandowski-Kurowicka-Joe (2009) transform.
#'
#' @param THETA Numerical vector of parameters.
#' @param Q Number of latent variables.
#'
#' @export
get_S <- function(THETA, Q) {
    .Call(`_plFA_get_S`, THETA, Q)
}

#' Get transformed parameters from latent correlation matrix
#'
#' Use Lewandowski-Kurowicka-Joe (2009) transformation on latent correlations
#' with Choleski decomposition.
#'
#' @param S Latent correlation matrix.
#' @export
get_par_from_S <- function(S) {
    .Call(`_plFA_get_par_from_S`, S)
}

